### ISSUE TITLE
Can we apply the Envmap properly?

### ISSUE THREAD

**Issue by rondoor124** [Fyrestar/THREE.extendMaterial#11]
Hi there!
How can we apply the envMap?
This is the related [link](https://threejs.org/docs/#api/en/scenes/Scene.environment) to show how envMap works on physic material
I tried to add the envMap texture into the uniforms, but it seems it does not work properly.
Do you have any suggestions about adding the envMap?
Thanks!

**Comment by Fyrestar** [comment]
Here's an example with envMap https://codepen.io/Fyrestar/pen/eYZovOw

**Comment by rondoor124** [comment]
Sorry. I just check it now. Yeah, this is so sick!
