### ISSUE TITLE
i cant get this example to work :o please

### ISSUE THREAD

**Issue by RollsChris** [Fyrestar/THREE.extendMaterial#16]
Hi I'm hoping someone here can help, I'm trying to use this library.. I have tried two methods using the CDN and pulling in the class that I want.. but nothing seems to be working :( .. 
weirdly everything works locally

[Sandbox](https://codesandbox.io/s/jolly-alex-h6i56h?file=/js/app.js)

![image](https://user-images.githubusercontent.com/6059035/212777438-dee7b5e2-17f2-4f0c-9adf-40e31594b0ed.png)

**Comment by Fyrestar** [comment]
I don't use codesandbox or parcel, you should also import it from "three" then it's right, but codesandbox does all kind of crazy things, one time it works, refreshing nothing changing suddenly it breaks something.

![image](https://user-images.githubusercontent.com/28584767/212851108-7817f7d0-91a8-4ebe-b149-86983728b13a.png)

If you open this, adding this line below the imports from "three" and remove the extendMaterial from the "three" import.
`import extendMaterial from "./extend.js";`
https://codesandbox.io/s/suspicious-morning-2miu4y?file=/js/app.js

It will faill, then you undo that all and it will work, but if you refresh it fails again. It's some issue parcel or codesandbox causes i suppose.

**Comment by RollsChris** [comment]
Wow thanks, that has just put me off codesandbox for life lol, I just tried Replit and it worked without no issues, i guess ill be switching... what's your favourite online code editor? seems a pain to share or embed Replit

**Comment by Fyrestar** [comment]
I only work locally, for editable demos and such i use codepen or my own server
